dependencies:
    - smartcontractkit/chainlink-brownie-contracts@0.4.0
    - aave/protocol-v2@1.0.1
compiler:
    solc:
        remappings:
            - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
            - "@aave=aave/protocol-v2@1.0.1"
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
# Change to trye to verify smart contracts
verify: False
# set a custom mnemonic for the development network
networks:
    default: mainnet-fork
    mainnet-fork:
        lending_pool_addresses_provider: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
        weth_token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
        # For mainnet, the link token is the same
        link_token: "0x514910771af9ca656af840dff83e8264ecf986ca"
        aave_link_token: "0x514910771af9ca656af840dff83e8264ecf986ca"
        aave_dai_token: "0x6b175474e89094c44da98b954eedeac495271d0f"
        dai_token: "0x6b175474e89094c44da98b954eedeac495271d0f"
        link_eth_price_feed: "0xDC530D9457755926550b59e8ECcdaE7624181557"
        dai_eth_price_feed: "0x773616E4d11A78F511299002da57A0a94577F1f4"
    kovan:
        vrf_coordinator: "0xdD3782915140c8f3b190B5D67eAc6dc5760C46E9"
        # https://aave.github.io/aave-addresses/kovan.json
        # Aave uses their own testnet tokens to ensure they
        # always have enough to play with.
        # find the most up to date token addresses in the above link
        aave_link_token: "0xAD5ce863aE3E4E9394Ab43d4ba0D80f419F61789"
        aave_dai_token: "0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD"
        link_token: "0xa36085F69e2889c224210F603D836748e7dC0088"
        keyhash: "0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4"
        fee: 100000000000000000
        oracle: "0x2f90A6D021db21e1B2A077c5a37B3C7E75D15b7e"
        jobId: "29fa9aa13bf1468788b7cc4a500a45b8"
        eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
        link_eth_price_feed: "0x3Af8C569ab77af5230596Acf0E8c2F9351d24C38"
        dai_eth_price_feed: "0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541"
        # You can get the address of the lending pool from the lending pool address provider
        # Sometimes the lending_pool address changes, so we want to get the address from there
        lending_pool_addresses_provider: "0x88757f2f99175387ab4c6a4b3067c77a695b0349"
        weth_token: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
wallets:
    from_key: ${PRIVATE_KEY}
    from_mnemonic: ${MNEMONIC}

    # could also do from_mnemonic, and you'd have to change the accounts.add to accounts.from_mnemonic
